output_dir: generation_result
time_limit: 36000 # seconds
max_generations: 10000
# debug: true

# node_class: SMILESStringNode
# use_canonical_smiles_as_key: true
# root: c1ccccc1

# transition_class: JensenTransition
# transition_args:
#   check_size: true
#   check_ring: true

# policy_class: PUCT
# policy_args:
#   c: 0.25
#   best_rate: 0.9

# generator_class: MCTS
# generator_args:
#   check_loop: true
#   cut_failed_child: true
#   n_evals: 1
#   n_tries: 1
#   filter_reward: -1
#   info_interval: 100

node_class: MolSentenceNode
use_canonical_smiles_as_key: true

device: cpu
transition_class: RNNTransition
transition_args:
  # model_dir: model/smiles/drugs_zinc/tf25_ported
  model_dir: model/smiles/drugs_zinc/gru
  # model_dir: model/smiles/drugs_zinc/lstm
  top_p: 0.995
  sharpness: 1

policy_class: UCT
policy_args:
  c: 0.1
  best_rate: 0.95

generator_class: MCTS
generator_args:
  eval_width: 1
  n_evals: 1
  n_tries: 3
  filter_reward:  0
  cut_terminal: true
  info_interval: 100

reward_class: GuacaMolReward
reward_args:
  objective: celecoxib_rediscovery

plot_args:
  x_axis: generation_order
  moving_average_window: 0.005
  reward_top_ps: [0.5, 0.1]

filters:
  - filter_class: ValidityFilter # put this first if unsure
  - filter_class: RadicalFilter