output_dir: generation_result
silent: true
time_limit: 1000 # Seconds
max_generations: 400
n_keys_to_pass: 4

node_class: MolSentenceNode
node_class_variables:
  use_canonical_smiles_as_key: true

device: cpu
transition_class: RNNTransition
transition_args:
  model_dir: model/smiles/drugs_zinc/gru
  top_p: 0.995

policy_class: UCT
policy_args:
  best_rate: 0.5
  c: 0.125

generator_class: MCTS
generator_args:
  n_eval_width: 1
  n_eval_iters: 1
  n_tries: 3
  filter_reward: 0
  avoid_duplicates: false
  terminal_reward: ignore

filters:
  - filter_class: ValidityFilter # Apply ValidityFilter first (unless molecular validity is already guaranteed), since other MolFilter and MolReward do not check validity by default.
  - filter_class: RadicalFilter
  - filter_class: WeightFilter
    max: 700
  - filter_class: HeavyAtomCountFilter
    max: 45
  - filter_class: RingBondFilter