output_dir: generation_result
silent: true
time_limit: 1000 # seconds
max_generations: 9800
node_class: SMILESStringNode
use_canonical_smiles_as_key: true

transition_class: JensenTransition
transition_args:
  check_size: true
  check_ring: true
  filters:
  - filter_class: ValidityFilter
  - filter_class: RadicalFilter

policy_class: PUCT
policy_args:
  c: 0.25
  best_rate: 0.9

generator_class: MCTS
generator_args:
  avoid_duplicates: true
  cut_failed_child: true
  n_eval_width: .inf
  n_eval_iters: 1
  n_tries: 1
  filter_reward: 0
  info_interval: 100

plot_args:
  reward_top_ps: [0.5, 0.1]
  save_only: true