output_dir: generation_result
silent: true
time_limit: 1000 # Seconds
max_generations: 9600
node_class: CanonicalSMILESStringNode
use_canonical_smiles_as_key: true

transition_class: JensenTransition
transition_args:
  check_size: false
  check_ring: true
  filters:
  - filter_class: ValidityFilter
  - filter_class: RadicalFilter

policy_class: PUCT
policy_args:
  c: 0.25
  best_rate: 0.95

generator_class: MCTS
generator_args:
  n_eval_width: 1
  n_eval_iters: 1
  n_tries: 1
  filter_reward: 0
  avoid_duplicates: true
  info_interval: 100

plot_args:
  reward_top_ps: [0.5, 0.1]
  save_only: true