output_dir: generation_result

model_class: GPT2Transition
model_dir: model/helm/pep_noperiod_1.2m
lang_class: HELM
lang_path: model/helm/helm_pep_noperiod.lang

reward_class: JScoreReward
reward_conf:
  filtered_reward: -2

policy_class: UCB
policy_conf:
  c:
    - [2, 0.0001]
    - [3, 1]
    - [4, 0.1]
    - [5, 0.01]

generation_conf:
  time_limit: 30 #seconds
  #max_rollouts : 15
  #max_generations : 1500
  expansion_threshold: 0.995
  exhaust_backpropagate: false
  use_dummy_reward: false
  change_root: false
  rollout_conf:
    rollout_threshold: 0.995

filters:
  - filter_class: ValidityFilter #put this first if unsure
