output_dir: generation_result
# time_limit: 10 # seconds
max_generations: 10000

# transition_class: GPT2Transition
# transition_args:
#   model_dir: model/helm/pep_noperiod_gpt2_1.2m
#   top_p: 0.995

device: cpu
transition_class: RNNTransition
transition_args:
  model_dir: model/helm/pep_noperiod_gru
  top_p: 0.995

reward_class: JScoreReward
# reward_class: LogPReward

policy_class: UCB1
policy_args:
  c: 0.1
  best_rate: 0.5
  # c:
  #   - [2, 0.0001]
  #   - [3, 1]
  #   - [4, 0.1]
  #   - [5, 0.01]

generator_class: MCTS
generator_args:
  rollout_width: 1
  n_rollouts: 1
  filtered_reward: -1

filters:
  - filter_class: ValidityFilter # put this first if unsure

plot_args:
  moving_average_window: 0.02