output_dir: generation_result

model_class_path: transition.gpt2.GPT2Transition
model_dir: model/smiles/smiles_drugs_zinc_1.2m
lang_class_path: language.smiles.SMILES
lang_path: model/smiles/smiles_drugs_zinc.lang

reward_class_path: reward.logp_reward.LogPReward
reward_conf:
  filtered_reward: -1

policy_class_path: policy.ucb.UCB
policy_conf:
  c: 0.1

generation_conf:
  time_limit: 15 #seconds
  #max_rollouts : 15
  #max_generations : 1500
  expansion_threshold: 0.995
  exhaust_backpropagate: false
  use_dummy_reward: false
  change_root: false
  rollout_conf:
    rollout_threshold: 0.95

filters:
  - filter_class_path: filter.validity_filter.ValidityFilter #put this first if unsure
  - filter_class_path: filter.lipinski_filter.LipinskiFilter
    filter_conf:
      rule_of: 5
  - filter_class_path: filter.logP_filter.LogPFilter
    filter_conf:
      min_logP: 0