model_conf:
  model_class_path: transition.gpt2.GPT2Transition
  model_dir: model/helm/pep_noperiod_1.2m
  lang_class_path: language.helm.HELM
  lang_path: model/helm/helm_pep_noperiod.lang

generator_conf:
  output_dir: generation_result
  reward_class_path: reward.logp_reward.LogPReward
  objective_values_conf:
  reward_conf:
    filtered_reward: -1
  policy_class_path: policy.ucb.UCB
  policy_conf:
    c: 0.01

generation_conf:
  time_limit: 5 #seconds
  #max_rollouts : 15
  #max_generations : 1500
  expansion_threshold: 0.995
  exhaust_backpropagate: false
  use_dummy_reward: false
  change_root: false
  rollout_conf:
    rollout_threshold: 0.995
