generator_conf:
  output_dir: result
  objective_values_conf:
  reward_conf:
    filtered_reward: -1
  policy_conf:
    c: 0.01

generation_conf:
  time_limit: 10 #seconds
  #max_rollouts : 15
  #max_generations : 1500
  expansion_threshold: 0.995
  exhaust_backpropagate: False
  use_dummy_reward: False
  change_root: False
  rollout_conf:
    rollout_threshold: 0.995
