output_dir: generation_result

model_class_name: GPT2Transition
model_dir: model/smiles/smiles_drugs_zinc_1.2m
lang_class_name: SMILES
lang_path: model/smiles/smiles_drugs_zinc.lang

reward_class_name: LogPReward
reward_conf:
  filtered_reward: -1

policy_class_name: UCB
policy_conf:
  #c: 0.1
  c:
    - [5, 1]
    - [10, 0.1]
    - [20, 0.01]

generation_conf:
  time_limit: 15 #seconds
  #max_rollouts : 15
  #max_generations : 1500
  expansion_threshold: 0.995
  exhaust_backpropagate: false
  use_dummy_reward: false
  change_root: false
  rollout_conf:
    rollout_threshold: 0.95

filters:
  - filter_class_name: ValidityFilter #put this first if unsure
  - filter_class_name: AromaticRingFilter
  - filter_class_name: LipinskiFilter
    rule_of: 5
  - filter_class_name: LogPFilter
    min_logP: 0
  - filter_class_name: RingSizeFilter
    max_ring_size: 6