output_dir: generation_result
time_limit: 1800 # seconds
max_generations: 10000
debug: true

node_class: MolStringNode
root: "[C][=C][C][=C][C][=C][Ring1][=Branch1]"

language_class: SELFIES

transition_class: BioT5Transition
transition_args:
  n_samples: 2
  target_objective: improve J score, which combines LogP, SA score, and ring size penalty.

reward_class: JScoreReward

policy_class: UCB1
policy_args:
  best_rate: 0.5
  c: 0.05
  # c:
  #   - [5, 1]
  #   - [10, 0.1]
  #   - [20, 0.01]

generator_class: MCTS
generator_args:
  rollout_width: 2
  n_rollouts: 1
  filtered_reward: -1
  freeze_terminal: true
  check_loop: true
  remove_failed_child: true
  info_interval: 1

filters:
  - filter_class: ValidityFilter # put this first if unsure
  # - filter_class: RadicalFilter
  # - filter_class: PubChemFilter
  # - filter_class: ChargeFilter
  # - filter_class: AromaticRingFilter
  # - filter_class: LipinskiFilter
  #   rule_of: 5
  # - filter_class: PainsFilter
  #   families:
  #     - A
  #     - B
  #     - C
  # - filter_class: MaxRingSizeFilter
  #   max: 6
  # - filter_class: RotatableBondsFilter
  #   min: 2
  # - filter_class: TPSAFilter
  # - filter_class: SAScoreFilter
  #   min: 3.5
  # - filter_class: WeightFilter
  #   min: 30
  # - filter_class: HBAFilter
  #   max: 5
  # - filter_class: HBDFilter
  #   max: 5