output_dir: generation_result
time_limit: 30 # seconds
# max_generations : 1500

# transition_class: GPT2Transition
# transition_conf:
#   model_dir: model/smiles/drugs_zinc_gpt2_3.2m
#   top_p: 0.995

device: cpu
transition_class: RNNTransition
transition_conf:
  model_dir: model/smiles/drugs_zinc_rnn

reward_class: LogPReward
filtered_reward: 0
# reward_conf:

policy_class: UCB
policy_conf:
  c: 0.2
  # c:
  #   - [5, 1]
  #   - [10, 0.1]
  #   - [20, 0.01]

# generator_class: MCTS
# generator_conf:
#   expansion_threshold: 0.995
#   use_dummy_reward: false
#   terminal_reward: -1

generator_class: MultiProcessMCTS
generator_conf:
  use_dummy_reward: false
  n_workers: 1

filters:
  - filter_class: ValidityFilter # put this first if unsure
  - filter_class: RadicalFilter
  # - filter_class: ChargeFilter
  # - filter_class: AromaticRingFilter
  # - filter_class: LipinskiFilter
  #   rule_of: 5
  # - filter_class: PainsFilter
  #   families:
  #     - A
  #     - B
  #     - C
  # - filter_class: MaxRingSizeFilter
  #   max: 6
  # - filter_class: RotatableBondsFilter
  #   min: 2
  # - filter_class: TPSAFilter
  # - filter_class: WeightFilter
  #   min: 30
  # - filter_class: HBAFilter
  #   max: 5
  # - filter_class: HBDFilter
  #   max: 5