output_dir: generation_result
time_limit: 10000 # seconds
node_class: MolSentenceNode
use_canonical_smiles_as_key: true

device: cpu
transition_class: RNNTransition
transition_args:
  model_dir: model/smiles/drugs_zinc/tf25_ported
  top_p: 0.995

policy_class: UCT
policy_args:
  c: 0.1
  best_rate: 0.95

generator_class: MCTS
generator_args:
  eval_width: 1
  n_evals: 1
  n_tries: 3
  filter_reward:  0
  cut_terminal: true
  info_interval: 100

reward_class: LogPReward # dummy

plot_args:
  x_axis: generation_order
  packed_objectives:
    - [egfr, erbb2, abl, src, lck, pdgfr_beta, vegfr2, fgfr1, ephb4]
  moving_average_window: 0.005
  reward_top_ps: [0.5, 0.1]

filters:
  - filter_class: ValidityFilter # put this first if unsure
  - filter_class: RadicalFilter
  - filter_class: PubChemFilter
  - filter_class: ChargeFilter
  - filter_class: AromaticRingFilter
  - filter_class: LipinskiFilter
    rule_of: 5
  - filter_class: PainsFilter
    families:
      - A
      - B
      - C
  - filter_class: MaxRingSizeFilter
    max: 6