output_dir: generation_result
time_limit: 10000 # seconds
max_generations: 100
node_class: MolSentenceNode
use_canonical_smiles_as_key: true

device: cpu
transition_class: RNNTransition
transition_args:
  model_dir: model/smiles/drugs_zinc/tf25_ported
  top_p: 0.995

policy_class: UCT
policy_args:
  c: 0.1
  best_rate: 0.95

generator_class: MCTS
generator_args:
  eval_width: 1
  n_evals: 1
  n_tries: 3
  filter_reward:  0
  cut_terminal: true
  info_interval: 1000

reward_class: LogPReward # dummy

filters:
  - filter_class: ValidityFilter # put this first if unsure
  - filter_class: RadicalFilter