model_conf:
  model_class_path: transition.gpt2.GPT2Transition
  model_dir: model/smiles/smiles_drugs_zinc
  lang_class_path: language.smiles.SMILES
  lang_path: model/smiles/smiles_drugs_zinc.lang

generator_conf:
  output_dir: result
  reward_class_path: reward.logp_reward.LogPReward
  objective_values_conf:
  reward_conf:
    filtered_reward: -1
  policy_class_path: policy.ucb.UCB
  policy_conf:
    c: 1

generation_conf:
  time_limit: 1200 #seconds
  #max_rollouts : 15
  #max_generations : 1500
  expansion_threshold: 0.995
  exhaust_backpropagate: false
  use_dummy_reward: false
  change_root: false
  rollout_conf:
    rollout_threshold: 0.95
