output_dir: generation_result

model_class: GPT2Transition
model_dir: model/smiles/smiles_drugs_zinc_1.2m
#lang_path: if not specified, uses model_dir/{model_dir_name}.lang

reward_class: JScoreReward
reward_conf:
  filtered_reward: -1

policy_class: UCB
policy_conf:
  #c: 0.1
  c:
    - [5, 1]
    - [10, 0.1]
    - [20, 0.01]

generation_conf:
  time_limit: 15 #seconds
  #max_rollouts : 15
  #max_generations : 1500
  expansion_threshold: 0.995
  exhaust_backpropagate: false
  use_dummy_reward: false
  change_root: false
  rollout_conf:
    rollout_threshold: 0.95

filters:
  - filter_class: ValidityFilter #put this first if unsure
  - filter_class: RadicalFilter
  - filter_class: ChargeFilter
  - filter_class: AromaticRingFilter
  - filter_class: LipinskiFilter
    rule_of: 5
  - filter_class: PainsFilter
    families:
      - A
      - B
      - C
  - filter_class: MaxRingSizeFilter
    max: 6
  # - filter_class: RotatableBondsFilter
  #   min: 2
  # - filter_class: TPSAFilter
  # - filter_class: WeightFilter
  #   min: 30
  # - filter_class: HBAFilter
  #   max: 5
  # - filter_class: HBDFilter
  #   max: 5