output_dir: generation_result
time_limit: 10 # seconds
# max_generations : 1500

transition_class: GPT2Transition
transition_conf:
  model_dir: model/helm/pep_noperiod_1.2m
  top_p: 0.995

reward_class: JScoreReward
filtered_reward: -0.5

policy_class: PUCT
policy_conf:
  c:
    - [2, 0.0001]
    - [3, 1]
    - [4, 0.1]
    - [5, 0.01]
  initial_mean: 0.5

generator_conf:
  expansion_threshold: 0.995
  exhaust_backpropagate: false
  use_dummy_reward: false

filters:
  - filter_class: ValidityFilter # put this first if unsure
