output_dir: generation_result

model_class: GPT2Transition
model_dir: model/helm/pep_noperiod_1.2m

reward_class: JScoreReward
reward_conf:
  filtered_reward: -1
  # params:
  #   EGFR: {type: max_gauss, alpha: 1, mu: 9, sigma: 2, weight: 8}
  #   ERBB2: {type: min_gauss, alpha: 1, mu: 2, sigma: 2, weight: 1}
  #   ABL: {type: min_gauss, alpha: 1, mu: 2, sigma: 2, weight: 1}
  #   SRC: {type: min_gauss, alpha: 1, mu: 2, sigma: 2, weight: 1}
  #   LCK: {type: min_gauss, alpha: 1, mu: 2, sigma: 2, weight: 1}
  #   PDGFRbeta: {type: min_gauss, alpha: 1, mu: 2, sigma: 2, weight: 1}
  #   VEGFR2: {type: min_gauss, alpha: 1, mu: 2, sigma: 2, weight: 1}
  #   FGFR1: {type: min_gauss, alpha: 1, mu: 2, sigma: 2, weight: 1}
  #   EPHB4: {type: min_gauss, alpha: 1, mu: 2, sigma: 2, weight: 1}
  #   Solubility: {type: max_gauss, alpha: 1, mu: -2, sigma: 0.6, weight: 1}
  #   Permeability: {type: max_gauss, alpha: 1, mu: 1, sigma: 1, weight: 1}
  #   Metabolic_stability: {type: max_gauss, alpha: 1, mu: 75, sigma: 20, weight: 1}
  #   Toxicity: {type: min_gauss, alpha: 1, mu: 5.5, sigma: 0.5, weight: 1}
  #   # SAscore is made negative when scaling because a smaller value is more desirable.
  #   SAscore: {type: max_gauss, alpha: 1, mu: -3, sigma: 2, weight: 1}
  #   QED: {type: max_gauss, alpha: 1, mu: 0.8, sigma: 0.25, weight: 1}
  #   molecular_weight: {type: rectangular, min: 200, max: 600, weight: 1}
  #   tox_alert: {type: identity, weight: 1}
  #   has_chembl_substruct: {type: identity, weight: 1}

policy_class: PUCT
policy_conf:
  c:
    - [2, 0.0001]
    - [3, 1]
    - [4, 0.1]
    - [5, 0.01]
  initial_mean: 0.5

generation_conf:
  time_limit: 10 #seconds
  #max_rollouts : 15
  #max_generations : 1500
  expansion_threshold: 0.995
  exhaust_backpropagate: false
  use_dummy_reward: false
  change_root: false
  rollout_conf:
    rollout_threshold: 0.995

filters:
  - filter_class: ValidityFilter #put this first if unsure
