output_dir: generation_result
# time_limit: 15 # seconds
max_generations: 1000
debug: true
seed: 0
node_class: MolSentenceNode

# transition_class: GPT2Transition
# transition_args:
#   model_dir: model/smiles/drugs_zinc/gpt2_1.2m
#   model_dir: model/helm/chembl_peptide/gpt2_1.2m

device: cpu
transition_class: RNNTransition
transition_args:
  # model_dir: model/smiles/drugs_zinc/tf25_ported
  # model_dir: model/smiles/drugs_zinc/gru
  model_dir: model/smiles/drugs_zinc/lstm
  # model_dir: model/helm/chembl_peptide/gru
  # top_p: 0.995


reward_class: LogPReward
filtered_reward: -0.5

generator_class: RandomGenerator

filters:
  - filter_class: ValidityFilter # put this first if unsure