study_name: guacamol_test
n_trials: 200000

output_dir: generation_result
time_limit: 3600 # seconds
silent: true
seed: 0
node_class: MolSentenceNode
use_canonical_smiles_as_key: true

device: cpu
transition_class: RNNTransition
transition_args:
  model_dir: model/smiles/drugs_zinc/tf25_ported

policy_class: UCT

generator_class: MCTS
generator_args:
  check_loop: false
  cut_terminal: true
  filter_reward: 0
  terminal_reward: ignore

reward_class: LogPReward # dummy

filters:
  - filter_class: ValidityFilter # put this first if unsure
  - filter_class: RadicalFilter