time_limit: 1600 # seconds
csv_output: false
silent: true
node_class: SMILESStringNode
use_canonical_smiles_as_key: true

transition_class: JensenTransition
transition_args:
  check_size: true
  check_ring: true
  filters:
  - filter_class: ValidityFilter # put this first if unsure
  - filter_class: RadicalFilter

policy_class: PUCT

generator_class: MCTS
generator_args:
  avoid_duplicates: true
  cut_failed_child: true
  cut_terminal: true
  n_evals: 1
  n_tries: 1
  filter_reward: 0
  info_interval: 100

filters: