study_name: mol_opt_chain
csv_output: false
silent: true

time_limit: 500 # seconds
node_class: MolSentenceNode
use_canonical_smiles_as_key: true

device: cpu
transition_class: RNNTransition
transition_args:
  model_dir: model/smiles/drugs_zinc/gru

policy_class: UCT

generator_class: MCTS
generator_args:
  eval_width: 1
  n_evals: 1
  n_tries: 3
  filter_reward:  0
  cut_terminal: true
  info_interval: 100

filters:
  - filter_class: ValidityFilter # put this first if unsure
  - filter_class: RadicalFilter