output_dir: generation_result
time_limit: 1800
max_generations: 10000
debug: true

node_class: SELFIESStringNode
root: "[C][=C][C][=C][C][=C][Ring1][=Branch1]"

transition_class: BioT5Transition
transition_args:
  n_samples: 3
  prompt: "Definition: You are given a molecule SELFIES. Your job is to generate a SELFIES molecule that improve LogP value. Now complete the following example - Input: <bom>###SELFIES###<eom> Output: "

reward_class: LogPReward

policy_class: UCT
policy_args:
  best_rate: 0.5
  c: 0.05

generator_class: MCTS
generator_args:
  eval_width: .inf
  n_evals: 1
  filter_reward: -1
  cut_terminal: true
  avoid_duplicates: true
  cut_failed_child: true
  info_interval: 1

plot_args:
  reward_top_ps: [0.5, 0.1]

filters:
  - filter_class: ValidityFilter
  - filter_class: ConnectivityFilter