output_dir: generation_result
time_limit: 1800 # Seconds
max_generations: 100
debug: true

node_class: SMILESStringNode
root: "c1ccccc1"
node_class_variables:
  use_canonical_smiles_as_key: true

transition_class: LongChatGPTTransition
transition_args:
  api_key_path: data/personal/api_key.txt
  model: gpt-4o-mini
  n_samples: 1
  prompt:
    - "Transform the given molecule to improve its drug-likeness while preserving the core scaffold. Starting molecule: ###KEY###."
    - "Transform the given molecule to improve its drug-likeness by appending a single fragment. Starting molecule: ###KEY###"
    - "Transform the given molecule to improve its drug-likeness by modifying a single fragment. Starting molecule: ###KEY###"
  initial_prompt: "Your ultimate goal is to generate molecules that maximize the reward (drug-likeness) by iteratively transforming the given ones. All molecules will be provided in SMILES format, and your response must return the result strictly as a SMILES string, without any additional text or explanation. Do not output any molecule that has already been generated previously."

reward_class: TDCReward
reward_args:
  objective: qed

policy_class: UCT
policy_args:
  best_rate: 0.5
  c: 0.05

generator_class: MCTS
generator_args:
  n_eval_width: .inf
  n_eval_iters: 1
  filter_reward: 0
  cut_terminal: true
  avoid_duplicates: true
  cut_failed_child: true
  info_interval: 1

plot_args:
  reward_top_ps: [0.5, 0.1]

filters:
  - filter_class: ValidityFilter