output_dir: generation_result
time_limit: 3600
max_generations: 18
debug: true

node_class: SMILESStringNode
root: "c1ccccc1"

transition_class: ChatGPTTransition
transition_args:
  api_key_path: data/personal/api_key.txt
  # model: gpt-5-mini
  model: gpt-4o-mini
  n_samples: 1
  prompt: 
    - "I will provide you with a molecule in SMILES format. Transform the given molecule to improve its drug-likeness while preserving the core scaffold, and return the result as a SMILES string only. Do not include any additional text or explanation in the output. Starting molecule: ###SMILES###"
    - "I will provide you with a molecule in SMILES format. Transform the given molecule to improve its drug-likeness by appending a single fragment, and return the result as a SMILES string only. Do not include any additional text or explanation in the output. Starting molecule: ###SMILES###"
    - "I will provide you with a molecule in SMILES format. Transform the given molecule to improve its drug-likeness by modifying a single fragment, and return the result as a SMILES string only. Do not include any additional text or explanation in the output. Starting molecule: ###SMILES###"

reward_class: TDCReward
reward_args:
  objective: qed

policy_class: UCT
policy_args:
  best_rate: 0.9
  c: 0.2

generator_class: MCTS
generator_args:
  eval_width: .inf
  n_evals: 1
  filter_reward: 0
  cut_terminal: true
  avoid_duplicates: true
  cut_failed_child: true
  info_interval: 1

plot_args:
  reward_top_ps: [0.5, 0.1]

filters:
  - filter_class: ValidityFilter