time_limit: 1000 # seconds
max_generations: 1000

output_dir: generation_result

node_class: SMILESStringNode
use_canonical_smiles_as_key: true

transition_class: JensenTransition
transition_args:
  check_size: true
  check_ring: true

# If not specified, the same reward will be used.
# reward_class: ~~~

# If not specified, the same filters will be used.
# filters:

policy_class: PUCT
policy_args:
  c: 0.5
  best_rate: 0.9

generator_class: MCTS
generator_args:
  avoid_duplicates: true
  cut_failed_child: true
  n_evals: 1
  n_tries: 1
  filter_reward: 0
  info_interval: 100

plot_args:
  reward_top_ps: [0.5, 0.1]