output_dir: generation_result
# time_limit: 10
max_generations: 3840 # 256*15
node_class: SentenceNode

# transition_class: ProtGPT2Transition
# transition_args:
#   max_length: 80
#   rollout_top_k: 950

transition_class: RNNTransition
transition_args:
  top_p: 0.99
  model_dir: model/fasta/gfp

reward_class: GFPReward
reward_args:
  mutation_penalty_strength: 0
  mutation_penalty_start: 10
  e_penalty_strength: 0
  e_penalty_start: -13

policy_class: UCT
policy_args:
  c: 0.2
  best_rate: 0.5

generator_class: MCTS
generator_args:
  n_eval_width: 1
  n_eval_iters: 1
  filter_reward: -1
  info_interval: 50

plot_args:
  reward_top_ps: [0.5, 0.1]
  moving_average_window: 0.02