output_dir: generation_result
# time_limit: 10
max_generations: 3840 # 256*15
node_class: FASTAStringNode
root: "SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTFSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIDFKEDGNILGHKLEYNYNSHNVYIMADKQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK" # avGFP
device: cpu

transition_class: RNNBasedMutation
transition_args:
  n_samples: 1
  rnn_top_p: 0.99
  model_dir: model/fasta/gfp

reward_class: GFPReward

policy_class: UCT
policy_args:
  c: 0.2
  best_rate: 0.5

generator_class: MCTS
generator_args:
  avoid_duplicates: true
  info_interval: 100

plot_args:
  reward_top_ps: [0.5, 0.1]
  moving_average_window: 0.02