output_dir: generation_result
# time_limit: 10 # seconds
max_generations: 5000
seed: 0
debug: true
node_class: MolSentenceNode

device: cpu
transition_class: RNNTransition
transition_args:
  model_dir: model/helm/chembl_peptide/gru
  top_p: 0.995

reward_class: JScoreReward
# reward_class: LogPReward

policy_class: UCT
policy_args:
  c: 0.1
  best_rate: 0.5

generator_class: MCTS
generator_args:
  eval_width: 1
  n_evals: 1
  filter_reward: -1

plot_args:
  reward_top_ps: [0.5, 0.1]

filters:
  - filter_class: ValidityFilter # put this first if unsure

plot_args:
  moving_average_window: 0.02