output_dir: generation_result
# time_limit: 20
max_generations: 10000
debug: true
node_class: MolSentenceNode

device: cpu
transition_class: RNNTransition
transition_args:
  model_dir: model/smiles/drugs_zinc/gru
  top_p: 0.995

reward_class: JScoreReward
# reward_args:

policy_class: UCT
policy_args:
  best_rate: 0.5
  c: 0.2

generator_class: MCTS
generator_args:
  n_eval_width: 1
  n_eval_iters: 1
  filter_reward: 0
  cut_terminal: true

plot_args:
  reward_top_ps: [0.5, 0.1]

filters:
  - filter_class: ValidityFilter