output_dir: generation_result
time_limit: 1000 # seconds
max_generations: 50000

node_class: SMILESStringNode
use_canonical_smiles_as_key: true

root: c1cc(ccc1)Nc2ncnc3c2cc(c(c3))
# goal: Brc1cc(ccc1)Nc2ncnc3c2cc(c(c3)OC)OC

reward_class: EGFRReward

transition_class: JensenTransition
transition_args:
  check_size: true
  check_ring: true
  filters:
    - filter_class: ValidityFilter # put this first if unsure
    - filter_class: RadicalFilter
    - filter_class: SubstructureFilter
      smiles: c1cc(ccc1)Nc2ncnc3c2cc(c(c3))

policy_class: PUCT
policy_args:
  c: 0.25
  best_rate: 0.9

generator_class: MCTS
generator_args:
  avoid_duplicates: true
  cut_failed_child: true
  n_evals: 1
  n_tries: 1
  filter_reward: -1
  info_interval: 100

plot_args:
  reward_top_ps: [0.5, 0.1]