output_dir: generation_result
max_generations: 500
node_class: FASTAStringNode

transition_class: ProtGPT2Transition
transition_args:
  max_length: 80
  rollout_top_k: 950

reward_class: LogPReward

filters:
  - filter_class: ValidityFilter

policy_class: UCT
policy_args:
  c: 0.1
  best_rate: 0.5

generator_class: MCTS
generator_args:
  n_eval_width: 1
  n_eval_iters: 1
  filter_reward: -1
  avoid_duplicates: false
  info_interval: 1

plot_args:
  reward_top_ps: [0.5, 0.1]
  moving_average_window: 0.02