output_dir: generation_result
time_limit: 36000
max_generations: 200000
node_class: CanonicalSMILESStringNode
root: "c1ccccc1"
# root: C
# root: c1ccccc1
# root: c1cccc2cncnc12

transition_class: SMIRKSTransition
transition_args:
  smirks_path:  data/smirks/gbga.txt
  filters:
  - filter_class: ValidityFilter
  - filter_class: MaxRingSizeFilter
  - filter_class: RingBondFilter
  - filter_class: RadicalFilter
  - filter_class: ChargeFilter
  # It is recommended to restrict the molecular size (via atom counts or molecular weight etc.) when using transitions like SMIRKSTransition or GBGATransition to prevent excessive growth of the search tree.
  - filter_class: HeavyAtomCountFilter
    max: 45

reward_class: JScoreReward

policy_class: PUCT
policy_args:
  c: 0.25
  best_rate: 0.9

generator_class: MCTS
generator_args:
  n_eval_iters: 1
  n_tries: 1
  filter_reward: ignore
  avoid_duplicates: true
  info_interval: 100

plot_args:
  reward_top_ps: [0.5, 0.1]