output_dir: generation_results
time_limit: 3600
max_generations: 18
debug: true

node_class: SMILESStringNode
root: "c1ccccc1"
node_class_variables:
  use_canonical_smiles_as_key: true

transition_class: ChatGPTTransition
transition_args:
  api_key_path: data/personal/api_key.txt
  # model: gpt-5-mini
  model: gpt-4o-mini
  n_samples: 1
  prompt: 
    - "I will provide you with a molecule in SMILES format. Modify the given molecule to the given molecule to improve its drug-likeness by adding, replacing, or modifying atoms and fragments. Generate as many candidate SMILES as possible, with each SMILES on a separate line and no additional text before or after the list. Starting molecule: ###STRING###"

reward_class: TDCReward
reward_args:
  objective: qed

policy_class: UCT
policy_args:
  best_rate: 0.9
  c: 0.2

generator_class: MCTS
generator_args:
  n_eval_width: .inf
  n_eval_iters: 1
  filter_reward: 0
  cut_terminal: true
  avoid_duplicates: true
  cut_failed_child: true
  info_interval: 1

# Use the generator below instead of the one above (MCTS) to parallelize transition
# generator_class: DoubleAsyncParallelMCTS
# generator_args:
#   inflight_type: separate
#   transition_dispatcher_type: thread
#   max_transition_inflight: 4 # Maximum number of transition threads
#   transition_loss: 0 # Temporary reward value backpropagated while a transition job is in flight, then reverted when the transition ends.
#   max_reward_inflight: 1
#   reward_dispatcher_type: disable # No reward parallelization

#   n_eval_width: .inf
#   n_eval_iters: 1
#   filter_reward: 0
#   cut_terminal: true
#   avoid_duplicates: true
#   cut_failed_child: true
#   info_interval: 1

plot_args:
  reward_top_ps: [0.5, 0.1]

filters:
  - filter_class: ValidityFilter
