output_dir: "sandbox/training_result/model"
lang_class: SMILES
dataset_path: data/smiles/250k_rndm_zinc_drugs_clean.smi
interval: "epoch"

n_embd: 96
n_layer: 4
n_head: 1
# additional_length: 0

training_args:
  overwrite_output_dir: True
  num_train_epochs: 100
  per_device_train_batch_size: 512
  per_device_eval_batch_size: 512
  save_total_limit: 2
  learning_rate: 0.001
  weight_decay: 0.01
  fp16: true
  report_to: none
  load_best_model_at_end: true