output_dir: generation_result
time_limit: 1000 # seconds
max_generations: 1000
node_class: MolSentenceNode
use_canonical_smiles_as_key: true

device: cpu
transition_class: RNNTransition
transition_args:
  model_dir: model/smiles/drugs_zinc/gru
  top_p: 0.995

reward_class: JScoreReward

policy_class: UCT
policy_args:
  best_rate: 0.5
  c: 0.2

generator_class: MCTS
generator_args:
  eval_width: 1
  n_evals: 1
  n_tries: 1
  filter_reward: -1
  terminal_reward: -1

filters:
  - filter_class: ValidityFilter # put this first if unsure
  - filter_class: RadicalFilter