output_dir: generation_result
time_limit: 1000 # seconds
max_generations: 500
n_keys_to_pass: 10

node_class: SELFIESStringNode
# root: "[C][=C][C][=C][C][=C][Ring1][=Branch1]"
root: "CCc1ccccc1"
use_canonical_smiles_as_key: true

# transition_class: BioT5Transition
transition_class: BioT5PlusTransition
transition_args:
  n_samples: 3
  target_objective: introduce a substructure of valsartan

reward_class: GuacaMolReward
reward_args:
  objective: valsartan_smarts

policy_class: UCT
policy_args:
  best_rate: 0.5
  c: 0.05

generator_class: MCTS
generator_args:
  eval_width: 3
  n_evals: 1
  filter_reward: -1
  cut_terminal: true
  check_loop: true
  cut_failed_child: true
  info_interval: 1

filters:
  - filter_class: ValidityFilter # put this first if unsure
  - filter_class: RadicalFilter