study_name: mol_opt_rnn
csv_output: false
silent: true

time_limit: 1000 # Seconds
node_class: MolSentenceNode
node_class_variables:
  use_canonical_smiles_as_key: true

device: cpu
transition_class: RNNTransition
transition_args:
  model_dir: model/smiles/drugs_zinc/tf25_ported
  top_p: 0.995
  v2_replication: true

policy_class: UCT

generator_class: MCTS
generator_args:
  eval_width: .inf
  n_evals: 3
  cut_failed_child: true
  info_interval: 100
  filter_reward: ignore
  failed_parent_reward: -1
  terminal_reward: -1
  avoid_duplicates: false
  cut_terminal: false

filters:
  - filter_class: ValidityFilter # Apply ValidityFilter first (unless molecular validity is already guaranteed), since other MolFilter and MolReward do not check validity by default.
  - filter_class: RadicalFilter